# Do not set project ID (app ID) here.

# Invoke: gcloud config set project $PROJECT_ID
# Before: ./gradlew :packages:prodAppEngine:appengineDeploy

# Or forget appengineDeploy and invoke:
# ./gradlew clean :packages:prodAppEngine:appengineStage
# Then deploy:
# ~/google-cloud-sdk/bin/gcloud app deploy packages/prodAppEngine/build/staged-app/app.yaml --project '$APP_ID'

# NOTE: Before deploy check the generated WAR. If the name is partial.war, wrong WAR is copied. Fix it.

runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
