# Do not set project ID (app ID) here.

# Invoke: gcloud config set project $PROJECT_ID
# Before: ./gradlew :packages:prodAppEngine:appengineDeploy

# Or forget appengineDeploy and invoke:
# ./gradlew clean :packages:prodAppEngine:appengineStage
# Then deploy:
# ~/google-cloud-sdk/bin/gcloud app deploy packages/prodAppEngine/build/staged-app/app.yaml --project '$APP_ID'

runtime: java
env: flex
